version: 0.2
phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r deployment_package.zip . # Empaqueta todo el proyecto, incluidos los node_modules
  post_build:
    commands:
      - echo "Updating lambda function..."
      - aws lambda update-function-code --function-name dynamiclambdagittest --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
artifacts:
  files:
    - deployment_package.zip
